Non_Prod:
  DB:
    TYPE: SQLSERVER
    SERVER: localhost
    DATABASE_INSTANCE_NAME: MSSQLSERVER
    PORT: 1433
    DATABASE: dfinrpt
    UID: no_need
    PWD: no_need

Prod:
  DB:
    TYPE: SQLSERVER
    SERVER: prod_server
    DATABASE_INSTANCE_NAME: MSSQLSERVER
    PORT: 1433
    DATABASE: dfinrpt
    UID: prod_user
    PWD: prod_password

